version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: flux-postgres
    environment:
      POSTGRES_DB: flux_wallet
      POSTGRES_USER: flux_user
      POSTGRES_PASSWORD: flux_password
    ports:
      - "5432:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/postgres_data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flux_user -d flux_wallet"]
      interval: 10s
      timeout: 5s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: flux_zookeeper
    environment:
      ZOOKEEPER_CLIENT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: flux_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNCECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092"]
      interval: 10s
      timeout: 10s
      retries: 5

  kafka_ui:
    image: provectuslabs/kafka-ui:latest
    container_name: flux_kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: flux-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
  

volumes:
  postgres_data:

